hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "ee7b28ddb985dd28f57826ca7c7435298460b05963d030d3bd3564874f5d0271"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/en_us.json"
hash = "4d1f98bda840eae7a095f2e969e85ca14555d0a5443e83b2c5bdf033ba9b703a"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/es_es.json"
hash = "c6af158e02fca9590d7f688d8a4bad410ccdabcb58787f0bd55c88a6543157f3"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/es_ve.json"
hash = "5e3660aff589b69711dba7347af9d030c545e76793ac6752111256a97edcc276"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/et_ee.json"
hash = "3ffce5d4f7b2efc2c98816d22871ef45fad912fded5606a9498a9d2f7ac7378a"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/fr_fr.json"
hash = "35b0783789f6735aa8cc8957c6f0bf5640d051bf9c6bdeeed5c508ab78b894e2"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/he_il.json"
hash = "cdf6c2143d6b4a6634c34a427ed849b15c5175c943a2474a5e3bfff6fab5b5da"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/it_it.json"
hash = "49d95b6a84e164b2e8e203e9772a6912ae23fc5c0fada8e26969c8f326f1cc90"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/pl_pl.json"
hash = "4ae15643ae98cc5121547cb787adc92b13161391f1d3572ab5b5bcd3d23acb53"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ro_ro.json"
hash = "f6afd3fa7e12990ed7181c04366bb5ce340a38981a2a54d8a95958b53bd8e296"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ru_ru.json"
hash = "f862137ff1847ac341f3f5f4571d157aa2b27c527d02240e239f64f1d96c6f5e"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/vi_vn.json"
hash = "4e7a3160e2ce7128a3fc583cd0a1cbb874b78eecb314ddbd9a0a209b7d3ee1a6"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zh_cn.json"
hash = "5ded8a669ee5be80278281c2a03477edc59e207e08f7addedfc144be6cf7dd08"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zh_tw.json"
hash = "15ca1dbab8723faf3a690cff0bdb0cbb63d20d138975083825c22c7a42643394"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "057cc80d73d0266e71bcc1d4471cba1d034a2d30f1aecca0bb2da050003f3483"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "feec37a3f444ce4d87ab540149fd7a9fdc0d5696a85054fc63697b7c19290353"

[[files]]
file = "config/modmenu.json"
hash = "9a04eaf0053e9b9c3f181ec7ebce30d00edee3f0c42214c6b57668fdcaf3fac2"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "375d545e83e1aabc7700c5f0bea4f7bcf1a19e5e35f9a2155bde2e1c9b0ebc61"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "9a04eaf0053e9b9c3f181ec7ebce30d00edee3f0c42214c6b57668fdcaf3fac2"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/sodium-shadowy-path-blocks-options.json"
hash = "4773ede8076bdbcfb6b8ea3de058a56120aa7438ee6b25de297c10aa8f5ce393"

[[files]]
file = "config/yosbr/options.txt"
hash = "69601bb677186426586f4c23bee782e079471781eb5535e13c6bbadaa092be64"

[[files]]
file = "mods/animatica.pw.toml"
hash = "e4871feb4abc954731ceb980476dd7500357f689daf5d9e4065c0f70aad18d03"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "a8321c6d297c9a266a82600942a2b329f374abb9f3fdd0810499a2f26a082b2d"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "352831e81514b1ed485bc36cee926b6e65a8eb0dcd15b3e2f8d95c7f7e58e509"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "de8e021e0beacab839ca3bd4dfdb30fa5f3cfd1e71be722ccf56373908b41a7f"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "d74e8bcb3c9e4fef65b56b636aab67f14810179cd41a2fc97e051f5eb1f84955"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "b8f6040c1859b1df8d144d71133809605005a35f10a7c54126fe19d135c772cd"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "be695a3492b1bbf044e6e5f018bbf10f6317db72ea2ce0b34ec7d46a83137bae"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "94f000249d21c4fc3b7744f9579bb6ac0d48e6bf4860fad16f23c997950a47f3"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "f3314d40956e7b3ca32f42f976a1c0704303e9f8f3c9792d402b3890e8550284"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "c76d23f24d4318c25c08c5bb55057af752fa8f60bd7989fc95eb23a223ab8228"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "3f793cb78a7b12af9f43914e55fd158789db5f69f69205a897e11cdd6569c367"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "93cabcba604035a35c4309a581907fb498b18785052397c5707335d5106d3743"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "c607b446f05ddb308290ce8ad1e769f60ec5e0445d4b7789a3855f1903dfa6f2"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "fb1f060f2eacbf88c8621adf0bd2fd67e71cb4c1ee0c4446fead3d90afb47f8e"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "eacf94908d2171da8e757139fe85d45e705962b6f0526536e8cc3d750e03a406"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "f8c57b83b826e6447a6a97f88f0fab03bb76caebc8272b74f3b890c6b5821d5d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f74d51ea05e79df7c581f0e28e916cb07761f66dbcb73b9a4888c1048bcf33af"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "894418c1146ab9a8086f6c9eadda0aad36c4fe2219e2199e4307f9273fed2dac"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "2892ef637c93b1255b6ee01eab9b27afa27fe42664094130ba0d560c8a320713"
metafile = true

[[files]]
file = "mods/paginated-advancements.pw.toml"
hash = "a1d5fa51ae5eabc1f6deaa345af2a8f548236f7d8ec75bcce942b99a5f0fadd5"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "2a948daed681901d76512b62ba4a3e68433745397f27d9158f08271d9ba0ad3c"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "692b7f775360faf75015ef40d93ed1992c29214dc9a7df60da88b4b7bdb101f3"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "4e673197e4526592d81b1b44b98b0605fa5b07ba29c6fefec4cd7b1ef33cff77"
metafile = true
