name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f9da38ad097437c645499bdee05b595a57e1a56fd32c23b4f03220b27b65627"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
