name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b6949d998cdd4f63c3bf95f4c887bead5fb26efe96f85de28ad0f3ef62c131d"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
