name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcc334f6cf64276aa89b01e44245b699d694e749f153339f3f18c624d623aa40"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
