name = "Fabulously Optimized"
author = "robotkoer"
version = "11.1.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71bf0321e8915cdd6f199c43751d48d2bd9f26a9d59b70e45d5ca7e98e64b277"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
